appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ufGdVk6l+P9Ooo5e+CsZG3kb5GsMPy4+5Z6H6wOt2I4dRFHS5+1ZKmGrbN4yyYizR72fNd8ki4C5XvV49dGx/MuXcOQPNnt76bKj3L/7WCzYZEO/iS+071+HqwPfXYZfOUJpSK2p8nPzNnn4R6aqeKYiAkRyF1293vz05qVEkMV8a5zzYq0i0OOBJbwjX6U9dHmd7dCoWAiRp99dfmgNXSZeq9AcryyDrKhfA2sfm3upOX+z1Nb1akTgZD2mU+gkqGd9s3FwC/B6BXN5D1ZRi/vZQ+iuItF88ziVcbOzSpZDdalXTrfrWgXiLeSU3NviPJrSnNmMi0gO5gSq3cH4ZnlcmZSOL2+BE63PVgGm4dDG9PumLpZJ0SyiByF3xSdY7+I8y/7EZw7BdzYIsWUddmquHWBpK3Ya2LJIavCnwcg9DWbi+pM8wFEiKVCRESsAaXdtAkcgpN2nilfk1GXPo800JIcufWBMwWWz549hmmFOTugZsClI5HRPrlTLqHEVnwrqo/IMjuvknFIFEcWwl6xodsaNuryfZ+y7pbZAfhS9uUbv7O5Hp60sxi67oT9kezGolLDQJ/2TmAhgOxrrO3u/rIPE+Dbw9/qBI65chbycTO/o2rCGn9/xKHZpVdUtFEzj2IGxSgfurcf4WcRcwAD04iGaGpXdXvk4OPslwfM=}
